CREATE DATABASE Pagina_Web;

USE Pagina_Web;

CREATE TABLE Registro_Clientes (
ID INT PRIMARY KEY AUTO_INCREMENT,
EMAIL VARCHAR(45) NOT NULL UNIQUE,
NOMBRE VARCHAR(45) NOT NULL,
APELLIDO VARCHAR(45) NOT NULL,
TELÉFONO VARCHAR(45) NOT NULL UNIQUE
);